Create CODE_OF_CONDUCT.md
KhalisFoundation/sttm-desktop pull request #1339
Opened 2021-04-10 01:01 UTC by tsingh777

2021-04-12 21:40 UTC, lbk003 requested changes

2021-04-12 21:40 UTC, lbk003 commented on CODE_OF_CONDUCT.md
> +  professional setting
No inflammatory or derogatory remarks towards Sikhism, or any other faith or religion.

2021-04-13 04:10 UTC, tsingh777 commented on CODE_OF_CONDUCT.md
> +  professional setting
Added

2021-04-18 17:56 UTC, lbk003 approved these changes

2021-04-18 18:17 UTC, merged