fix: show misc slide text on bani overlay screen
KhalisFoundation/sttm-desktop pull request #1629
Opened 2022-07-27 09:32 UTC by Gauravjeetsingh

![Peek 2022-07-27 15-00](https://user-images.githubusercontent.com/1990932/181213912-725db0da-c62b-488e-acbd-0e6bca54259d.gif)

Fixes issue #1542

2022-08-16 04:35 UTC, theamanjs requested changes

2022-08-16 04:35 UTC, theamanjs commented on www/obs/index.html
> +      var writeText = function(text, isGurmukhi, isAnnoucement) {
Veerji does it has to be `var`?

2022-08-18 05:25 UTC, Gauravjeetsingh commented on www/obs/index.html
> +      var writeText = function(text, isGurmukhi, isAnnoucement) {
It does not, thank you! pushed the fix.

2022-08-22 07:32 UTC, theamanjs approved these changes

2022-08-22 08:07 UTC, merged