add padding option
KhalisFoundation/sttm-desktop pull request #2018
Opened 2024-12-21 19:44 UTC by gurjit03

2025-04-14 06:17 UTC, saintsoldierx commented
@Gauravjeetsingh @inderpreetsingh can we get this reviewed and merged please?

2025-04-17 22:52 UTC, indersinghkhalis commented on www/main/common/store/GlobalState.js
> +    }),
can we do something along the lines of

```
const sendUpdateViewerSetting = (target) => {
  target.send(
    'update-viewer-setting',
    JSON.stringify({
      payload,
      actionName: 'setPadding',
      settingType: 'viewerSettings',
    }),
  );
};

if (global.webview) {
  sendUpdateViewerSetting(global.webview);
}

if (global.platform?.ipc) {
  sendUpdateViewerSetting(global.platform.ipc);
}

```

to remove any duplicate code?

2025-04-17 23:17 UTC, indersinghkhalis commented
@Gauravjeetsingh lets fasttrack this and get this merged. I have done a high level review from my side, but would love for you to take a look.

2025-04-18 11:10 UTC, Gauravjeetsingh requested changes
**Design Considerations for Current Implementation:**
Minor thing: Setting the top margin to 0 causes the "Padding Tools" label to overlap with the padding options menu, which affects readability of the option:
<img width="712" alt="image" src="https://github.com/user-attachments/assets/cbf1163a-3866-4d41-8284-e4622381de38" />
Additionally, the label "Padding" may not be intuitive for non-technical users. It might be worth reconsidering the terminology to make its function more self-explanatory.

Referring back to the problem statement outlined in #2013, the primary goal is to reduce padding to accommodate more text on the screen. However, the visual difference between the default padding and setting padding to zero appears minimal:

With default padding: <img width="1509" alt="image" src="https://github.com/user-attachments/assets/0b84b2a1-fcbf-4964-acfd-6e0a46c1efa0" />

With padding set to 0: <img alt="image" src="https://github.com/user-attachments/assets/25009a3a-e982-4a7b-85e8-f748878459f2" />

Could we investigate specific shabads or screen sizes where reducing padding meaningfully increases the visible text area? Testing those edge cases would help determine whether this feature effectively addresses the problem.

This investigation would also clarify whether there’s ever a need to increase the right and bottom padding, which are currently defaulted to 0.

2025-04-18 11:37 UTC, gurjit03 commented
> **Design Considerations for Current Implementation:** Minor thing: Setting the top margin to 0 causes the "Padding Tools" label to overlap with the padding options menu, which affects readability of the option: <img alt="image" width="712" src="https://private-user-images.githubusercontent.com/1990932/435169258-cbf1163a-3866-4d41-8284-e4622381de38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQ5NzU2MzAsIm5iZiI6MTc0NDk3NTMzMCwicGF0aCI6Ii8xOTkwOTMyLzQzNTE2OTI1OC1jYmYxMTYzYS0zODY2LTRkNDEtODI4NC1lNDYyMjM4MWRlMzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDQxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA0MThUMTEyMjEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjZkYmMzNDYwZjNmYTJlYzA0NDY2ZjE3ODJlOTllODEwZDc2NDNkZjRiYjdjM2MwNzU2NzA2ODdmYTBkYWVhZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.L0TDm5wuxHPjdrrSE6BDPHnevjiXnYa5MqJ23hECl3U"> Additionally, the label "Padding" may not be intuitive for non-technical users. It might be worth reconsidering the terminology to make its function more self-explanatory.
> 
Yes, that's right. Would it be alright to display the two fields side by side? Also, regarding the naming, I think we can go with spacing or border-spacing. Let me know if you have any other suggestions!

> Referring back to the problem statement outlined in #2013, the primary goal is to reduce padding to accommodate more text on the screen. However, the visual difference between the default padding and setting padding to zero appears minimal:
> 
> With default padding: <img alt="image" width="1509" src="https://private-user-images.githubusercontent.com/1990932/435171509-0b84b2a1-fcbf-4964-acfd-6e0a46c1efa0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQ5NzU2MzAsIm5iZiI6MTc0NDk3NTMzMCwicGF0aCI6Ii8xOTkwOTMyLzQzNTE3MTUwOS0wYjg0YjJhMS1mY2JmLTQ5NjQtYWNmZC02ZTBhNDZjMWVmYTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDQxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA0MThUMTEyMjEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzdmYjY4NDk1OWRmMzk3NTJjODhhNDE5MzhhMGM5ODMwMDBlZjU2MzBlYzU2ZTY0MWEzOTYwZTIyNjlkZGE5MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.W-mf1le7zdo7rYwft3vp5zrhRM2DzkShFNxqYQ7YUz8">
> 
> With padding set to 0: ![image](https://private-user-images.githubusercontent.com/1990932/435170977-25009a3a-e982-4a7b-85e8-f748878459f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQ5NzU2MzAsIm5iZiI6MTc0NDk3NTMzMCwicGF0aCI6Ii8xOTkwOTMyLzQzNTE3MDk3Ny0yNTAwOWEzYS1lOTgyLTRhN2ItODVlOC1mNzQ4ODc4NDU5ZjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDQxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA0MThUMTEyMjEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTlmODZlYTNiZWQyNzM2YjI0Mzg4YmViODVkMDE0NWMyOGJlZjE0YWY4YzMwNDM5YmRhYzBiZTQ1YTU3NjA0NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.l6JIXUqR6F1PodfNzXQrPwgcxtnJS5PMRt7_mcBcWQk)
> 
> Could we investigate specific shabads or screen sizes where reducing padding meaningfully increases the visible text area? Testing those edge cases would help determine whether this feature effectively addresses the problem.
> This investigation would also clarify whether there’s ever a need to increase the right and bottom padding, which are currently defaulted to 0.
I think that’s a really good observation. From my conversation with @saintsoldierx veerji, the issue seems to be:

“Some Gurdwara projectors are placed quite far from the screen, causing the projected image to go off the edges. So we need a way to add extra padding or margins on any side to fix that.”

To me, it sounds like adding customizable side padding should help manage this. I’ve also added an upper limit to the padding so things don’t get too out of hand.

If you have any other thoughts or suggestions, would love to hear your input!

2025-04-18 11:38 UTC, gurjit03 commented on www/main/common/store/GlobalState.js
> +    }),
@indersinghkhalis thanks ji, will have a look asap.

2025-04-18 19:40 UTC, indersinghkhalis commented
I agree with the requirement of customizable padding, while we might do a better job in providing that solution, i thinking providing A solution is better.

2025-04-23 16:05 UTC, indersinghkhalis commented
@Gauravjeetsingh  i think padding a standard term for what we are accomplishing here. But yeah let's do all the other changes.

2025-05-22 11:16 UTC, Gauravjeetsingh commented
@gurjit03 veerji, Any update on this one?

2025-06-06 10:44 UTC, Gauravjeetsingh commented
I am getting blank white screen in viewer after merging changes, and there are few linter issues as well.

2025-07-29 06:09 UTC, Gauravjeetsingh approved these changes

2025-07-29 06:09 UTC, merged